trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .devops/adm-rg.bicep
      - .devops/app-rg.bicep
      - .devops/site-build.bicep
      - .devops/role-assign.bicep
      - .devops/pipeline/_deploy-container.yml
      - .devops/pipeline/_provision-app-service.yml
      - .devops/pipeline/azure-pipelines-infrastructure.yml
      - .devops/pipeline/azure-pipelines-release-infrastructure.yml

resources:
  - repo: self

pool:
  vmImage: 'ubuntu-22.04'

name: $(Build.BuildId)

parameters:
  - name: sites_1
    type: object
    default:
      - sacramento|1|100
      - stanislaus|1|101
      - butte|1|102
      - humboldt|1|103
      - merced|1|104
      - siskiyou|1|105
      - nccourt|1|106
      - tehama|1|107
  - name: sites_2
    type: object
    default:
      - sierra|1|108
      - sanbenito|1|109
      - glenn|1|110
      - supremecourt|1|111
      - fresno|1|112
      - newsroom|1|113
      - sf|2|200
      - santabarbara|2|201
  - name: sites_3
    type: object
    default:
      - riverside|2|202
      - partners|2|203
      - oc|2|204
      - mendocino|2|205
      - monterey|2|206
      - slo2|2|207
      - sc|2|208
  - name: sites_4
    type: object
    default:
      - madera|2|209
      - napa|2|210
      - inyo|2|211
      - mariposa|2|212
      - alpine|2|213
      - tuolumne|2|214
      - deprep|2|215
      - alameda|2|216
  - name: sites_5
    type: object
    default:
      - kern|2|217
      - tularesuperiorcourt|2|218
      - sonoma|3|300
      - eldorado|3|301
      - imperial|3|302
      - kings|3|303
      - sutter|3|304
      - mono|3|305
  - name: sites_6
    type: object
    default:
      - colusa|3|306
      - modoc|3|307
      - yuba|3|308
      - trinity|3|309
      - srl|3|310
      - elcondado|3|311
      - idm|3|312
      - amdr|3|313
      - lake|3|314

variables:
  imageRepository: 'build/trialcourt/$(Build.SourceBranchName)'
  dockerfilePath: '$(Build.SourcesDirectory)/.devops/drupal-nginx-fpm/0.6-devops/Dockerfile'
  containerRegistry: 'globalctcmscr.azurecr.io'
  tag: 'build_$(Build.BuildId)-$(Build.SourceVersion)'
  location: 'West US 3'
  siteEnvPrefix: ''
  uniqueMod: '1'

  siteId1: ''
  siteName1: ''
  siteFarmId1: ''
  ResourceGroupName1: ''
  siteId2: ''
  siteName2: ''
  siteFarmId2: ''
  ResourceGroupName2: ''
  siteId3: ''
  siteName3: ''
  siteFarmId3: ''
  ResourceGroupName3: ''
  siteId4: ''
  siteName4: ''
  siteFarmId4: ''
  ResourceGroupName4: ''
  siteId5: ''
  siteName5: ''
  siteFarmId5: ''
  ResourceGroupName5: ''
  siteId6: ''
  siteName6: ''
  siteFarmId6: ''
  ResourceGroupName6: ''

  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    azureServiceConnection: 'PROD Resource Manager'
  ${{ elseif eq(variables['Build.SourceBranchName'], 'stage') }}:
    azureServiceConnection: 'UAT Resource Manager'
  ${{ else }}:
    azureServiceConnection: 'INT resource Manager'

stages:

  - stage: Manifest
    displayName: Manifest
    jobs:
      - job: SetPrefix
        displayName: Read manifest file
        steps:
          - script: |
              case $(Build.SourceBranchName) in
                master)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]prod"
                  ;;
                stage)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]uat"
                  ;;
                *)
                  echo "##vso[task.setvariable variable=siteEnvPrefix;isOutput=true;]int"
                  ;;
              esac
            displayName: 'Set Environment Prefix'
            name: EnvironmentPrefix
          - script: echo "$(EnvironmentPrefix.siteEnvPrefix)"
            displayName: 'Display Prefix'
          - script: |
              rm -rf $(Build.ArtifactStagingDirectory)/manifest.txt
              touch $(Build.ArtifactStagingDirectory)/manifest.txt

              rm -rf $(Build.ArtifactStagingDirectory)/build-image.txt
              echo $(tag) > $(Build.ArtifactStagingDirectory)/build-image.txt

              cp -r $(Build.SourcesDirectory)/.devops/scripts/trigger-release-infrastructure-pipeline.ps1 $(Build.ArtifactStagingDirectory)
            displayName: 'Initialize drop files'
      - job: ProcessSites1
        displayName: Process 1st set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_1 }}:
            - script: |
                IFS='|'
                read -a siteInfo <<< "${{site}}"
                echo "CountyId: ${siteInfo[0]}"
                echo "CountyName : ${siteInfo[2]}"
                echo "FarmId : ${siteInfo[1]}"
                echo "##vso[task.setvariable variable=siteId1;]${siteInfo[2]}"
                echo "##vso[task.setvariable variable=siteFarmId1;]${siteInfo[1]}"
                echo "##vso[task.setvariable variable=siteName1;]${siteInfo[0]}"
                echo "##vso[task.setvariable variable=ResourceGroupName1;]-ctcms-df${siteInfo[1]}-app-rg"
              displayName: 'SITE: ${{ site }}'
            - template: /.devops/pipeline/_provision-app-service.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                resourceGroupName: $(ResourceGroupName1)
                location: $(location)
                siteFarmId: $(siteFarmId1)
                siteId:  '$(siteEnvPrefixLocal)$(siteId1)'
                siteName: $(siteName1)
                uniqueMod: $(uniqueMod)
                buildId: $(Build.BuildId)
            - template: /.devops/pipeline/_deploy-container.yml
              parameters:
                azureServiceConnection: $(azureServiceConnection)
                siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                siteId: '$(siteEnvPrefixLocal)$(siteId1)'
                uniqueMod: $(uniqueMod)
                siteFarmId: $(siteFarmId1)
                containerRegistry: $(containerRegistry)
                sourceBranchName: $(Build.SourceBranchName)
                tag: 'latest'
      - job: ProcessSites2
        displayName: Process 2nd set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_2 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"
                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteId2;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId2;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName2;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName2;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'
              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName2)
                  location: $(location)
                  siteFarmId: $(siteFarmId2)
                  siteId: '$(siteEnvPrefixLocal)$(siteId2)'
                  siteName: $(siteName2)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)
              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId2)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId2)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'
      - job: ProcessSites3
        displayName: Process 3rd set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_3 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"
                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteId3;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId3;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName3;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName3;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'
              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName3)
                  location: $(location)
                  siteFarmId: $(siteFarmId3)
                  siteId: '$(siteEnvPrefixLocal)$(siteId3)'
                  siteName: $(siteName3)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)
              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId3)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId3)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'
      - job: ProcessSites4
        displayName: Process 4th set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_4 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"
                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteId4;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId4;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName4;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName4;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'
              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName4)
                  location: $(location)
                  siteFarmId: $(siteFarmId4)
                  siteId: '$(siteEnvPrefixLocal)$(siteId4)'
                  siteName: $(siteName4)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)
              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId4)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId4)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'
      - job: ProcessSites5
        displayName: Process 5th set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_5 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"
                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteId5;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId5;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName5;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName5;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'
              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName5)
                  location: $(location)
                  siteFarmId: $(siteFarmId5)
                  siteId: '$(siteEnvPrefixLocal)$(siteId5)'
                  siteName: $(siteName5)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)
              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId5)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId5)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'
      - job: ProcessSites6
        displayName: Process 6th set
        dependsOn: ['ReadManifest']
        variables:
          siteEnvPrefixLocal: $[ dependencies.ReadManifest.outputs['EnvironmentPrefix.siteEnvPrefix'] ]
        steps:
          - ${{ each site in parameters.sites_6 }}:
              - script: |
                  IFS='|'
                  read -a siteInfo <<< "${{site}}"
                  echo "CountyId: ${siteInfo[0]}"
                  echo "CountyName : ${siteInfo[2]}"
                  echo "FarmId : ${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteId6;]${siteInfo[2]}"
                  echo "##vso[task.setvariable variable=siteFarmId6;]${siteInfo[1]}"
                  echo "##vso[task.setvariable variable=siteName6;]${siteInfo[0]}"
                  echo "##vso[task.setvariable variable=ResourceGroupName6;]-ctcms-df${siteInfo[1]}-app-rg"
                displayName: 'SITE: ${{ site }}'
              - template: /.devops/pipeline/_provision-app-service.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  resourceGroupName: $(ResourceGroupName6)
                  location: $(location)
                  siteFarmId: $(siteFarmId6)
                  siteId: '$(siteEnvPrefixLocal)$(siteId6)'
                  siteName: $(siteName6)
                  uniqueMod: $(uniqueMod)
                  buildId: $(Build.BuildId)
              - template: /.devops/pipeline/_deploy-container.yml
                parameters:
                  azureServiceConnection: $(azureServiceConnection)
                  siteEnvPrefixLocal: $(siteEnvPrefixLocal)
                  siteId: '$(siteEnvPrefixLocal)$(siteId6)'
                  uniqueMod: $(uniqueMod)
                  siteFarmId: $(siteFarmId6)
                  containerRegistry: $(containerRegistry)
                  sourceBranchName: $(Build.SourceBranchName)
                  tag: 'latest'
